  services:
    app:
      build: ./
      ports:
        - 1111:1111
      depends_on:
        db:
          condition: service_healthy
          restart: true
        redis:
          condition: service_started
      environment:
        - PGHOST=db
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - PGPORT=5432
        - REDISHOST=redis
        - REDISPORT=6379
        - TZ=Europe/Moscow
      volumes:
        - ./files:/files
        - ./config:/config
      stop_grace_period: 5s
    db:
      image: postgres:latest
      volumes:
        - ./.db/postgres/data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - "2222:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 10s
      stop_grace_period: 5s
    redis:
      image: redis:latest
      ports:
        - "3333:6379"
      command: redis-server --requirepass root
      stop_grace_period: 5s

