# Render Blueprint для Go-приложения с Postgres и Redis
services:
  - type: web
    name: my-app
    plan: free
    env: docker
    buildCommand: docker build -t my-app .
    envVars:
      - key: PGHOST
        fromDatabase:
          name: my-db
          property: host
      - key: POSTGRES_USER
        fromDatabase:
          name: my-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: my-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: my-db
          property: database
      - key: PGPORT
        fromDatabase:
          name: my-db
          property: port
      - key: REDISHOST
        fromService:
          type: redis
          name: my-redis
          property: host
      - key: REDISPORT
        fromService:
          type: redis
          name: my-redis
          property: port
      - key: TZ
        value: Europe/Moscow
    healthCheckPath: /health

  - type: redis
    name: my-redis
    plan: free


databases:
  - name: my-db
    plan: free
