# Render Blueprint для Go-приложения с Postgres и Redis
services:
  - type: web
    name: my-app
    plan: free
    env: docker
    buildCommand: docker build -t my-app .
    startCommand: docker run -p 1111:1111 my-app
    envVars:
      - key: PGHOST
        fromDatabase:
          name: my-db
          property: hostname
      - key: POSTGRES_USER
        fromDatabase:
          name: my-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: my-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: my-db
          property: database
      - key: PGPORT
        value: "5432"
      - key: REDISHOST
        fromService:
          name: my-redis
          property: hostname
      - key: REDISPORT
        value: "6379"
      - key: TZ
        value: Europe/Moscow
    healthCheckPath: /health

  - type: redis
    name: my-redis
    plan: free

databases:
  - name: my-db
    plan: free