app:
  name: "playoo"
  version: "1.0.0"

server:
  host: "localhost"
  port: ":1111"

postgres:
  host: "your_db_host"
  port: "your_db_port"
  database: "your_db"
  user: "your_db_user"
  password: "your_db_password"

redis:
  host: "your_redis_host"
  port: "your_redis_port"
  password: "your_redis_password"

bot:
  token: "your_tg_bot_token"

auth:
  secret: "your_secret"